# Generated by Django 3.0.2 on 2021-04-15 00:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20210414_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dislikes',
            new_name='dislikes_count',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='likes_count',
        ),
        migrations.RemoveField(
            model_name='like',
            name='created',
        ),
        migrations.AlterField(
            model_name='post',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 0, 15, 3, 630196, tzinfo=utc)),
        ),
    ]
