# Generated by Django 3.0.2 on 2021-04-15 00:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20210415_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 0, 29, 12, 355136, tzinfo=utc)),
        ),
    ]
