# Generated by Django 3.0.2 on 2021-04-15 00:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20210415_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 0, 54, 38, 497480, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
