# Generated by Django 3.0.2 on 2021-04-15 20:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20210415_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='post',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 20, 55, 58, 984146, tzinfo=utc)),
        ),
    ]
