# Generated by Django 3.0.2 on 2021-04-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20210415_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
