# Generated by Django 3.0.2 on 2021-04-15 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20210415_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='expiration_time',
        ),
    ]
