# Generated by Django 3.0.2 on 2021-04-15 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_post_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expiration_time',
            field=models.TimeField(default=datetime.timedelta(0, 120)),
        ),
    ]
