# Generated by Django 3.0.2 on 2021-04-15 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20210415_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_expired',
        ),
    ]
