# Generated by Django 3.0.2 on 2021-04-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_remove_post_is_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expiration_time',
            field=models.DateTimeField(default='00:02:00'),
        ),
    ]
