# Generated by Django 3.0.2 on 2021-04-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_auto_20210416_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
