# Generated by Django 3.0.2 on 2021-04-16 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_auto_20210416_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='expiration_time',
            field=models.TimeField(default='00:02:00'),
        ),
    ]
