# Generated by Django 3.0.2 on 2021-04-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_auto_20210416_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expiration_time',
            field=models.DurationField(),
        ),
    ]
